
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# window rules - move to workspace
windowrule = workspace 1, class:^(steam_app_.*)
windowrulev2 = workspace 2, class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$
windowrulev2 = workspace 3, class:^([Dd]iscord|[Dd]iscordCanary|com.discordapp.DiscordCanary)$
windowrulev2 = workspace 4 silent, class:^([Ss]team)$
windowrulev2 = workspace 5, class:^([Dd]ocker\ Desktop)$
windowrulev2 = workspace 6, initialTitle:^(gsr\ ui)$


# window rules - float
windowrulev2 = float, class:^(pavucontrol|org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(CUSTOM_CLASS_NETWORK_TUI)$
windowrulev2 = float, class:^(steam)$, title:negative:^Steam$

windowrulev2 = float, title:^(gsr\ ui)$
windowrulev2 = float, initialTitle:^(gsr\ ui)$
windowrulev2 = norounding, title:^(gsr\ ui)$

# window rules - center
windowrulev2 = center, class:^(pavucontrol|org.pulseaudio.pavucontrol)

# window rules - size
windowrulev2 = size 60% 80%, class:^(pavucontrol|org.pulseaudio.pavucontrol)$
windowrulev2 = size 50% 80%, class:^(CUSTOM_CLASS_NETWORK_TUI)$

# window rules - opacity
windowrulev2 = opacity 0.9 0.8, class:^(kitty)$

# picture-in-picture rules
## firefox
windowrulev2 = float, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = pin, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = move 2231 78, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = size 500 280, class:^(firefox)$, title:^(Picture-in-Picture)$

## discord
windowrulev2 = float, class:^([Dd]iscord|[Dd]iscordCanary|com.discordapp.DiscordCanary)$, initialTitle:^(Discord\ Popout)$
windowrulev2 = pin, class:^([Dd]iscord|[Dd]iscordCanary|com.discordapp.DiscordCanary)$, initialTitle:^(Discord\ Popout)$
windowrulev2 = move 2206 78, class:^([Dd]iscord|[Dd]iscordCanary|com.discordapp.DiscordCanary)$, initialTitle:^(Discord\ Popout)$
windowrulev2 = size 525 297, class:^([Dd]iscord|[Dd]iscordCanary|com.discordapp.DiscordCanary)$, initialTitle:^(Discord\ Popout)$
