# workspace monitors
workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3

# workspace on-created-empty rules
workspace = 2, on-created-empty:firefox
workspace = 4, on-created-empty:steam
